import { describe, expect, it } from "vitest";
import { OpenApiPlaywrightGenerator } from "../src/openapi-playwright-generator";
import { TestUtils } from "./utils/test-utils";

describe("Statistics Generation", () => {
	const fixtureFile = TestUtils.getFixturePath("simple-api.yaml");

	describe("Client Statistics", () => {
		it("should include statistics in client file when showStats is true", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			// Use a private method reflection workaround
			const clientFileOutput = (generator as any).generateClientFile();

			expect(clientFileOutput).toContain("// Auto-generated by @cerios/openapi-to-zod-playwright");
			expect(clientFileOutput).toContain("// Do not edit this file manually");
			expect(clientFileOutput).toContain("// Client Statistics:");
			expect(clientFileOutput).toContain("//   Total endpoints:");
			expect(clientFileOutput).toContain("//   HTTP methods:");
			expect(clientFileOutput).toContain("//   Unique path parameters:");
			expect(clientFileOutput).toContain("//   Generated at:");
		});

		it("should not include statistics in client file when showStats is false", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: false,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			expect(clientFileOutput).not.toContain("// Client Statistics:");
			expect(clientFileOutput).not.toContain("//   Total endpoints:");
			expect(clientFileOutput).not.toContain("//   HTTP methods:");
		});

		it("should calculate correct endpoint count", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// simple-api.yaml has 4 endpoints:
			// GET /users, POST /users, GET /users/{userId}, DELETE /users/{userId}
			expect(clientFileOutput).toMatch(/Total endpoints:\s*4/);
		});

		it("should list all HTTP methods used", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Should contain DELETE, GET, POST (alphabetically sorted)
			expect(clientFileOutput).toMatch(/HTTP methods:\s*DELETE,\s*GET,\s*POST/);
		});

		it("should count unique path parameters", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// simple-api.yaml has 1 unique path parameter: userId
			expect(clientFileOutput).toMatch(/Unique path parameters:\s*1/);
		});

		it("should include ISO timestamp", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Check for ISO 8601 format (YYYY-MM-DDTHH:mm:ss.sssZ)
			expect(clientFileOutput).toMatch(/Generated at:\s*\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/);
		});
	});

	describe("Service Statistics", () => {
		it("should include statistics in service file when showStats is true", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			expect(serviceFileOutput).toContain("// Auto-generated by @cerios/openapi-to-zod-playwright");
			expect(serviceFileOutput).toContain("// Do not edit this file manually");
			expect(serviceFileOutput).toContain("// Service Statistics:");
			expect(serviceFileOutput).toContain("//   Total methods:");
			expect(serviceFileOutput).toContain("//   With response validation:");
			expect(serviceFileOutput).toContain("//   With query parameters:");
			expect(serviceFileOutput).toContain("//   Schema imports:");
			expect(serviceFileOutput).toContain("//   Type imports:");
			expect(serviceFileOutput).toContain("//   Generated at:");
		});

		it("should not include statistics in service file when showStats is false", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: false,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			expect(serviceFileOutput).not.toContain("// Service Statistics:");
			expect(serviceFileOutput).not.toContain("//   Total methods:");
			expect(serviceFileOutput).not.toContain("//   With response validation:");
		});

		it("should calculate correct method count", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			// simple-api.yaml has 4 methods
			expect(serviceFileOutput).toMatch(/Total methods:\s*4/);
		});

		it("should count methods with response validation", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			// Check the count (this depends on the fixture)
			expect(serviceFileOutput).toMatch(/With response validation:\s*\d+/);
		});

		it("should count methods with query parameters", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			expect(serviceFileOutput).toMatch(/With query parameters:\s*\d+/);
		});

		it("should count schema and type imports", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			expect(serviceFileOutput).toMatch(/Schema imports:\s*\d+/);
			expect(serviceFileOutput).toMatch(/Type imports:\s*\d+/);
		});

		it("should include ISO timestamp", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			// Check for ISO 8601 format (YYYY-MM-DDTHH:mm:ss.sssZ)
			expect(serviceFileOutput).toMatch(/Generated at:\s*\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z/);
		});
	});

	describe("Statistics with different OpenAPI specs", () => {
		it("should handle spec with no endpoints", () => {
			const emptyFixture = TestUtils.getFixturePath("empty-api.yaml");
			const generator = new OpenApiPlaywrightGenerator({
				input: emptyFixture,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			expect(clientFileOutput).toMatch(/Total endpoints:\s*0/);
			expect(clientFileOutput).toMatch(/HTTP methods:\s*$/m); // Empty list
			expect(clientFileOutput).toMatch(/Unique path parameters:\s*0/);
		});

		it("should handle spec with multiple path parameters", () => {
			const multiParamFixture = TestUtils.getFixturePath("multi-param-api.yaml");
			const generator = new OpenApiPlaywrightGenerator({
				input: multiParamFixture,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Should count all unique path parameters across all endpoints
			expect(clientFileOutput).toMatch(/Unique path parameters:\s*\d+/);
		});

		it("should handle spec with all HTTP methods", () => {
			const allMethodsFixture = TestUtils.getFixturePath("all-methods.yaml");
			const generator = new OpenApiPlaywrightGenerator({
				input: allMethodsFixture,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Should list methods alphabetically
			expect(clientFileOutput).toContain("HTTP methods:");
			// The exact methods depend on the fixture
		});
	});

	describe("Statistics consistency", () => {
		it("should show same endpoint count in client and service statistics", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();
			const serviceFileOutput = (generator as any).generateServiceFile(
				TestUtils.getOutputPath("service.ts"),
				TestUtils.getOutputPath("schemas.ts"),
				TestUtils.getOutputPath("client.ts")
			);

			// Extract endpoint/method counts
			const clientMatch = clientFileOutput.match(/Total endpoints:\s*(\d+)/);
			const serviceMatch = serviceFileOutput.match(/Total methods:\s*(\d+)/);

			expect(clientMatch).toBeTruthy();
			expect(serviceMatch).toBeTruthy();
			if (clientMatch && serviceMatch) {
				expect(clientMatch[1]).toBe(serviceMatch[1]);
			}
		});
	});

	describe("Statistics format", () => {
		it("should format statistics as comments", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Each line should start with //
			const statsLines = clientFileOutput.split("\n").filter((line: string) => line.includes("Statistics:"));
			expect(statsLines.length).toBeGreaterThan(0);

			const allStatsLines = clientFileOutput
				.split("\n")
				.filter(
					(line: string) =>
						line.trim().startsWith("//") &&
						(line.includes("Statistics:") ||
							line.includes("Total") ||
							line.includes("HTTP methods:") ||
							line.includes("Generated at:"))
				);

			for (const line of allStatsLines) {
				expect(line.trim()).toMatch(/^\/\//);
			}
		});

		it("should place statistics before imports", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			const statsIndex = clientFileOutput.indexOf("// Client Statistics:");
			const importIndex = clientFileOutput.indexOf("import type");

			expect(statsIndex).toBeGreaterThan(-1);
			expect(importIndex).toBeGreaterThan(-1);
			expect(statsIndex).toBeLessThan(importIndex);
		});

		it("should include blank line between statistics and code", () => {
			const generator = new OpenApiPlaywrightGenerator({
				input: fixtureFile,
				showStats: true,
			});

			const clientFileOutput = (generator as any).generateClientFile();

			// Statistics should be followed by a blank line before imports
			expect(clientFileOutput).toMatch(/Generated at:.*\n\nimport/s);
		});
	});
});
